### ISSUE TITLE
کلن اسامی و تایتل‌های ارائه دهندگان :دی

### ISSUE THREAD

**Issue by ssheikholeslami** [linuxfestival/8th-LinuxFest-Website#2]
همانطور که اسامی فارسی هستن، تایتل‌ها هم فارسی بشن :دی
- امیرحسین‌ پی‌براه، پژوهشگر در SICS
- جادی میرمیرانی، گیک لینوکس
- بهادر بخشی، استادیار دانشکده مهندسی کامپیوتر و فناوری اطلاعات دانشگاه صنعتی امیرکبیر
- علی نادعلیزاده، مدیر فنی تاد
- فراز شمشیردار، برنامه‌نویس در CNext
- محمدحسین حیدری، توسعه‌دهنده نرم‌افزار
- پرهام الوانی، توسعه دهنده‌ی نرم‌افزارهای متن‌باز
- سینا شیخ‌الاسلامی، دبیر اسبق انجمن علمی دانشجویی دانشکده مهندسی کامپیوتر
- پویا پارسا، توسعه‌دهنده‌ی نرم‌افزار

**Comment by pi0** [comment]
thnx, done
