### ISSUE TITLE
Admin Email

### ISSUE THREAD

**Issue by 1995parham** [linuxfestival/8th-LinuxFest-Website#31]
I think html formatting of admin emails are not okey, can I try to improve it ?

**Comment by anewage** [comment]
It's your call. Any contribution will be appreciated. :-D

**Comment by 1995parham** [comment]
👍

**Comment by anewage** [comment]
@1995parham It wasn't interesting enough?  😄

**Comment by 1995parham** [comment]
نه وقت نشده برم سراغش :دی
