### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by 1995parham** [linuxfestival/8th-LinuxFest-Website#9]
I get following error when I try to connect [Linux Festival Website](https://linuxfest.ir/) from my [Firefox](https://www.mozilla.org/en-US/firefox/) browser:  

> An error occurred during a connection to linuxfest.ir. Peer reports it experienced an internal error. (Error code: ssl_error_internal_error_alert)

**Comment by ssheikholeslami** [comment]
Try http instead of https .

--- Original Message ---

**Comment by 1995parham** [comment]
I tried http but I got the same error again.

**Comment by fshamshirdar** [comment]
you browser cache the request.

On Fri, May 8, 2015 at 12:18 AM, Parham Alvani notifications@github.com
wrote:

> I tried http but I got the same error again.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/pi0/LinuxFestival/issues/9#issuecomment-99994403.

## 

Faraz Shamshirdar | Robotic Center of Excellence
http://autman.aut.ac.ir
fb.com/faraz.shamshirdar | (+98) 936 575 8740
Amirkabir UofT http://aut.ac.ir, 424 Hafez Ave, Tehran, Iran, 15875-4413.
+98 (21) 64540
